# Linear systems: Some basic related to matrices in Python and example of Gaussian Elimination (two by two matrix) in floating point arithmetic 

04/11/2025

Francesca Mazzia

 Creative Commons Attribuzione-Non commerciale-Non Opere Derivate 2.5 Italy License http://creativecommons.org/licenses/by-nc-nd/2.5/it/

### Matrices and Vectors

In [2]:
import numpy as np
A = np.array([6., 5., 6.]) # we use numpy
print(A)

[6. 5. 6.]


In [4]:
A.size

3

In [6]:
A.shape

(3,)

no difference with array between row vectors and column vectors

In [259]:
A[0] + A[1] + A[2]

17.0

In [260]:
np.sum(A)

17.0

In [261]:
np.min(A)

5.0

In [262]:
np.argmin(A)

1

In [263]:
A[np.argmin(A)]

5.0

In [264]:
np.argmax(A)

0

In [265]:
A[np.argmax(A)]

6.0

In [266]:
A=np.array([[  3.,   5.,   7.],
           [  8.,   9.,  10.],
           [  2.,   3.,   5.]])
A

array([[ 3.,  5.,  7.],
       [ 8.,  9., 10.],
       [ 2.,  3.,  5.]])

In [267]:
A[0,0]

3.0

In [268]:
A[:,0]

array([3., 8., 2.])

In [269]:
A[0,]

array([3., 5., 7.])

In [270]:
A[1:3,1:3]

array([[ 9., 10.],
       [ 3.,  5.]])

example of use of linspace 

In [271]:
import numpy as np
x = np.linspace(-50,-1,5)
print(x)
type(x)
np.size(x)

[-50.   -37.75 -25.5  -13.25  -1.  ]


5

In [272]:
x=1e2
x

100.0

Example of random matrices

In [273]:
# np.random.rand : uniform distribution
A = np.random.rand(3,4)*10
print(A)

[[9.16750894 1.32311284 1.54782867 3.90574657]
 [3.91093395 0.52090292 4.1705552  1.58739446]
 [9.19707496 5.93387121 5.89911384 4.68663038]]


In [274]:

# square matrix with integer elements
A = np.random.randint(10,size=(3,3))
print(A)

[[4 9 3]
 [7 8 8]
 [6 8 4]]


In [275]:
# Elements of the matrix with column and row index
print(A[0,0])
print(A[1,1])
print(A[2,2])

4
8
4


In [276]:
print(type(A))

<class 'numpy.ndarray'>


In [277]:
C=np.array([[0,0,1,0,1],[1,0,0,0,1],[0,0,0,1,1],[0,1,0,0,1],[1,1,1,1,0]])
C

array([[0, 0, 1, 0, 1],
       [1, 0, 0, 0, 1],
       [0, 0, 0, 1, 1],
       [0, 1, 0, 0, 1],
       [1, 1, 1, 1, 0]])

Transpose

In [278]:
print('transpose\n',C.T)

transpose
 [[0 1 0 0 1]
 [0 0 0 1 1]
 [1 0 0 0 1]
 [0 0 1 0 1]
 [1 1 1 1 0]]


In [279]:
np.dot(C,C)

array([[1, 1, 1, 2, 1],
       [1, 1, 2, 1, 1],
       [1, 2, 1, 1, 1],
       [2, 1, 1, 1, 1],
       [1, 1, 1, 1, 4]])

Product row by column of a matrix

In [280]:
print(np.dot(A,A))
print(A@A)
# the following is not the correct operator
print(A*A)
print(A)

[[ 97 132  96]
 [132 191 117]
 [104 150  98]]
[[ 97 132  96]
 [132 191 117]
 [104 150  98]]
[[16 81  9]
 [49 64 64]
 [36 64 16]]
[[4 9 3]
 [7 8 8]
 [6 8 4]]


In [281]:
U=np.triu(A)   # triangula part of A
print(type(U)) # 
print(U)

<class 'numpy.ndarray'>
[[4 9 3]
 [0 8 8]
 [0 0 4]]


In [282]:
A.shape  # numero di righe e colonne

(3, 3)

In [283]:
A.ndim  # dimensione della matrice, possiamo avere array a piu' dimensioni

2

In [284]:
O = np.zeros( (3,3) ) # matrice nulla
print(O)
print(type(O))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [285]:
I = np.eye(3) # matrice identità
print(type(I))
print(I)

<class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [286]:
d = np.diag(np.array([1, 2, 3, 4])) # diagonal matrix
print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [287]:
narray = np.arange(1,10,2) # arange array
print(narray)

[1 3 5 7 9]


In [288]:
B = np.empty((3,4) ) # empty array
print(B)

[[9.16750894 1.32311284 1.54782867 3.90574657]
 [3.91093395 0.52090292 4.1705552  1.58739446]
 [9.19707496 5.93387121 5.89911384 4.68663038]]


In [289]:
C=np.empty((3,5))
print(C)

[[0.         0.         0.4472136  0.0531494  0.18257419]
 [0.4472136  0.2125976  0.36514837 0.4472136  0.4783446 ]
 [0.54772256 0.4472136  0.85039041 0.73029674 0.4472136 ]]


In [290]:
a = np.arange(10) 
print(a)
print('--- change the order ---')
print(a[::-1])      # ordine inverso

[0 1 2 3 4 5 6 7 8 9]
--- change the order ---
[9 8 7 6 5 4 3 2 1 0]


In [291]:
# computational time without loop
import time
n = 1000000
a = np.arange(n)
t1=time.process_time()
b = a + 1  
t2=time.process_time()
t2a=time.process_time()-t1
print(t2a)

0.0014599999999997948


In [292]:
# computational time with loop
l = range(n)
b = np.empty(n)
t1=time.process_time()
for i in l: 
    b[i]=i+1 
t2b=time.process_time()-t1
print(t2b)

0.15345500000000012


In [293]:
 a = np.array([1, 2, 3, 4])
 b = np.array([4, 2, 2, 4])
 a == b


array([False,  True, False,  True])

In [294]:
a > b


array([False, False,  True, False])

In [295]:
 np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [296]:
np.sin(a[0])

0.8414709848078965

linalg.solve for the solution of one linear system

In [297]:
A = np.random.rand(3,3)
b = np.array([1,2,3])
x = np.linalg.solve(A,b)
print(x)
print(type(x))

[  8.14028703 -25.37678422  16.61274355]
<class 'numpy.ndarray'>


In [298]:
print('type of A =',type(A))
print('residual =', np.dot(A,x)-b) 

type of A = <class 'numpy.ndarray'>
residual = [ 4.44089210e-16 -1.77635684e-15  8.88178420e-16]


In [299]:
# remember: the array vector does not are row vectors or column vectors
y = x.T
print(y.shape)

print('A*x = ',A*x)
print('A*y-A*x =', A*y-A*x)
print(' A = ', A)
print(' x = ', x)
print('A[:,0]*x[0] = ', A[:,0]*x[0])
print('A[:,1]*x[1] =', A[:,1]*x[1])
print( 'A[:,2]*x[2] =',A[:,2]*x[2])


(3,)
A*x =  [[  7.10141262  -6.1304757    0.02906309]
 [  0.0936056  -12.01397689  13.9203713 ]
 [  1.40158158  -9.25839289  10.85681131]]
A*y-A*x = [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
 A =  [[0.87237865 0.24157812 0.00174945]
 [0.01149905 0.47342393 0.83793332]
 [0.1721784  0.36483712 0.65352308]]
 x =  [  8.14028703 -25.37678422  16.61274355]
A[:,0]*x[0] =  [7.10141262 0.0936056  1.40158158]
A[:,1]*x[1] = [ -6.1304757  -12.01397689  -9.25839289]
A[:,2]*x[2] = [ 0.02906309 13.9203713  10.85681131]


Gaussian elimination in floating point arithmetic

In [300]:
import numpy as np
ex = 2
par = 1.0e-17 # 10^(-17)
if ex==1:
# Example 1 well conditioned
 A=np.array( [[par,1.],[1., 2.]])
 b= np.array([[1.],[3.]])
else:
# Example 2 ill conditioned, but a scaling could solve the problem
 A=np.array( [[10.,1./par],[1., 2.]])
 b= np.array([[1./par],[3.]])


print(A)
print(b)

[[1.e+01 1.e+17]
 [1.e+00 2.e+00]]
[[1.e+17]
 [3.e+00]]


In [301]:
Ah = np.hstack((A,b))
print(Ah)

[[1.e+01 1.e+17 1.e+17]
 [1.e+00 2.e+00 3.e+00]]


In [302]:
Ah[1,:]=Ah[1,:]-Ah[0,:]*(Ah[1,0]/Ah[0,0])
print(Ah)

[[ 1.e+01  1.e+17  1.e+17]
 [ 0.e+00 -1.e+16 -1.e+16]]


solve the upper triangular system

In [303]:
xg = np.zeros((2,1))
xg[1]= Ah[1,2]/Ah[1,1]
xg[0]= (Ah[0,2]-Ah[0,1]*xg[1])/Ah[0,0]
print('Solution after Gaussian Elimination \n',xg)

Solution after Gaussian Elimination 
 [[1.6]
 [1. ]]


In [304]:
x = np.linalg.solve(A,b)
print('linalg solve algorithm \n',x)
print("condition number",np.linalg.cond(A))

linalg solve algorithm 
 [[1.6]
 [1. ]]
condition number 9.999999999999998e+16


Solution of a lower triangular linear system:

In [305]:
#definiamo la function
import numpy as np

def solL(L,b):
    """
    Solution of a lower triangular system,
    implementation by row 
    INPUT  =matrix L, known term b
    OUTPUT =solution x
    
    """
    (n,m) = np.shape(b)
    x = np.zeros((n,1))
    x[0]=b[0]/L[0,0]
    for i in range(1,n):
        x[i]=(b[i] - np.dot(L[i,0:i],x[0:i]))/L[i,i]
    return x

n=100
L  = np.tril(np.random.rand(n,n))+np.eye(n)*1
xt = np.ones((n,1))
b  = np.dot(L,xt)
x  = solL(L,b)
print('absolute error')
print( np.max(abs(x-xt)))
print("determinant",np.prod(np.diag(L)) )
print("condition number",np.linalg.cond(L))

absolute error
3.375077994860476e-14
determinant 2.517540908386396e+16
condition number 1128.1683480138436
