# ORTHOGONALITY

02/04/2020

Francesca Mazzia

license: Creative Commons non-commercial not derivative works - 2.5 Italy License http://creativecommons.org/licenses/by-nc-nd/2.5/it/

###  Orthogonal  matrices

In [3]:
import scipy as sp
import numpy as np
import  scipy.stats as sst

M = sst.ortho_group.rvs(dim=3)
print('Orthogonal Random matrix: \n',M)

Orthogonal Random matrix: 
 [[-0.47447151 -0.08060625 -0.87657254]
 [-0.83852789  0.34439868  0.4222091 ]
 [-0.26785774 -0.93535671  0.23099795]]


In [5]:
print('dot product: \n', np.dot(M,M.T))
# M M^T = I identity matrix  M^T is the inverse of an orthogonal matrix (orthogonal matrix square matrix)

dot product: 
 [[ 1.00000000e+00  7.45113912e-18 -8.80921135e-17]
 [ 7.45113912e-18  1.00000000e+00  4.67014116e-17]
 [-8.80921135e-17  4.67014116e-17  1.00000000e+00]]


In [7]:
print('dot product: \n', np.dot(M.T,M))
# M^T M = I identity matrix

dot product: 
 [[ 1.00000000e+00  4.80572986e-17  3.70947613e-17]
 [ 4.80572986e-17  1.00000000e+00 -7.75227071e-17]
 [ 3.70947613e-17 -7.75227071e-17  1.00000000e+00]]


In [9]:
print('Determinant: \n',sp.linalg.det(M)) # det = -1 or det = 1

Determinant: 
 -0.9999999999999999


### Generic random matrix
Uniform distribution 

In [12]:
A= np.random.rand(5,3)
print('Generic Random matrix: \n',A)

Generic Random matrix: 
 [[0.52682108 0.84679263 0.29768453]
 [0.05172564 0.38168386 0.58010763]
 [0.69265093 0.11894647 0.27088331]
 [0.1011912  0.44348649 0.17521656]
 [0.07698733 0.60513555 0.52689008]]


In [14]:
rk=np.linalg.matrix_rank(A)
print('Rank of A:', rk)

Rank of A: 3


the vectors are not orthogonal

In [16]:
print(np.linalg.norm(np.dot(A.T,A)-np.eye(A.shape[1]))) # to check orthogonality of columns

1.7612376351788814


In [ ]:
print(np.linalg.norm(np.dot(A,A.T)-np.eye(A.shape[0])))

to orthogonalize it we use the Gram-Schmidt procedure on a set of linearly independent vectors columns of a matrix

In [18]:
def Gram_Schmidt(X):
    (m,n) = X.shape
    U = np.zeros((m,n))
    R = np.zeros((n,n))
    for i in range(n):
        U[:,i] = X[:,i]
        for j in range(i):
            R[j,i] = np.dot(U[:,j], X[:,i])
            U[:,i] = U[:,i] - R[j,i]*U[:,j]
        R[i,i]= np.linalg.norm(U[:,i])   
        U[:,i] = U[:,i]/R[i,i]
    return (U,R)

In [20]:
(U,R) = Gram_Schmidt(A)
print(U)

[[ 0.5979858   0.43191072 -0.49616024]
 [ 0.05871291  0.35493301  0.71245278]
 [ 0.78621649 -0.47310849  0.31661119]
 [ 0.11486044  0.37695116 -0.19724178]
 [ 0.08738703  0.56705544  0.32724468]]


In [22]:
print(np.dot(U.T,U))# the columns are an an orthonormale set

[[ 1.00000000e+00  2.34541871e-17 -1.27392447e-16]
 [ 2.34541871e-17  1.00000000e+00  1.22526662e-16]
 [-1.27392447e-16  1.22526662e-16  1.00000000e+00]]


In [24]:
print(np.dot(U,U.T)) # we have not the identity because the rows are not an orthonormal set

[[ 7.90308872e-01 -1.65081885e-01  1.08715779e-01  3.29357688e-01
   1.34807726e-01]
 [-1.65081885e-01  6.37013615e-01  1.03809760e-01  1.07461816e-05
   4.39543825e-01]
 [ 1.08715779e-01  1.03809760e-01  9.42210655e-01 -1.50482575e-01
  -9.59642861e-02]
 [ 3.29357688e-01  1.07461816e-05 -1.50482575e-01  1.94189416e-01
   1.59243192e-01]
 [ 1.34807726e-01  4.39543825e-01 -9.59642861e-02  1.59243192e-01
   4.36277442e-01]]


In [26]:
B = np.random.rand(3,3)
rk=np.linalg.matrix_rank(A)
print('Rank of A:', rk)
(UB,RB) = Gram_Schmidt(B)
print('UB \n',UB)
print('RB \n',RB)

Rank of A: 3
UB 
 [[ 0.95663054 -0.2756269  -0.09427524]
 [ 0.26561051  0.69241665  0.67082802]
 [ 0.1196205   0.66677507 -0.73559632]]
RB 
 [[0.59368068 1.17504771 1.06438619]
 [0.         0.75961631 0.43506139]
 [0.         0.         0.36085431]]


In [28]:
print(np.dot(UB.T,UB))

[[ 1.00000000e+00 -2.15318153e-16  5.04871784e-18]
 [-2.15318153e-16  1.00000000e+00  1.01924628e-15]
 [ 5.04871784e-18  1.01924628e-15  1.00000000e+00]]


In [30]:
print(np.dot(UB,UB.T))

[[ 1.00000000e+00 -3.42824032e-16  3.20116376e-17]
 [-3.42824032e-16  1.00000000e+00 -1.37709328e-16]
 [ 3.20116376e-17 -1.37709328e-16  1.00000000e+00]]


In [32]:
print('B \n',B)
print('B-np.dot(UB,RB) \n', B-np.dot(UB,RB))

B 
 [[0.56793307 0.91471584 0.86429009]
 [0.15768783 0.838076   0.82602709]
 [0.07101638 0.64705301 0.1519674 ]]
B-np.dot(UB,RB) 
 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]


To generate an orthogonal basis we use the QR factorization

In [35]:
(Q,R)=np.linalg.qr(B)
print('Q: \n',Q)
print('R: \n',R)

Q: 
 [[-0.95663054  0.2756269   0.09427524]
 [-0.26561051 -0.69241665 -0.67082802]
 [-0.1196205  -0.66677507  0.73559632]]
R: 
 [[-0.59368068 -1.17504771 -1.06438619]
 [ 0.         -0.75961631 -0.43506139]
 [ 0.          0.         -0.36085431]]


In [37]:
print(RB)
print(UB)

[[0.59368068 1.17504771 1.06438619]
 [0.         0.75961631 0.43506139]
 [0.         0.         0.36085431]]
[[ 0.95663054 -0.2756269  -0.09427524]
 [ 0.26561051  0.69241665  0.67082802]
 [ 0.1196205   0.66677507 -0.73559632]]


 ### Exercise

In [39]:
A=np.array([ [-1, 1, 0],[0,-1,1]])
print(A)

[[-1  1  0]
 [ 0 -1  1]]


In [41]:
AAT=np.dot(A,A.T)
print('AAT\n',AAT)
ATA=np.dot(A.T,A)
print('ATA\n',ATA)

AAT
 [[ 2 -1]
 [-1  2]]
ATA
 [[ 1 -1  0]
 [-1  2 -1]
 [ 0 -1  1]]


In [ ]:
(SU,U)=np.linalg.eig(AAT)
print('Eigenvalues of AAT: \n',SU)
print('Eigenvectors of AAT : \n',U)

In [ ]:
print(np.dot(U.T,U))

In [ ]:
(SV,V)=np.linalg.eig(ATA)
print('Eigenvalues of ATA : \n',SV)
print('Eigenvectors of ATA : \n',V)

In [ ]:
RS=np.dot(np.dot(U.T,A),V)

In [ ]:
print('Matrix RS of the singular value decomposition \n',RS)

In [ ]:
Us, ss, Vs = np.linalg.svd(A, full_matrices=True)
print(ss)